#! /usr/bin/env bash

# Loop notes:
# 1. xargs -r   no action is taken when input is empty
# 2. ls -1      format output one entry per line
# 3. tail -1    select last line in list generated by ls

FOLDERS=(
  introduction
  getting-started
  menu-design-patterns
  disclosure-nav-menu
  conclusion
)

for folder in ${FOLDERS[@]} ; do
  f=`find $folder -name "*.md" -print0 | xargs -r ls -1 | tail -1`
  if [ ! -z $f ]; then sed -e '$s/$/\n/' $f ; fi
done > article.md
